### ISSUE TITLE
API request with Youtube URL does not download video

### ISSUE THREAD

**Issue by e-alfred** [e-alfred/ocdownloader#37]
Trying to download a Youtube video with one of the browser extensions returns the following message: "Unable to retrieve true Youtube video URL"

This seems to be caused by issuing a JSON request with the Youtube URL over the API from an external tool.

**Comment by e-alfred** [comment]
The corresponding issue on the client side: https://github.com/DjazzLab/ocDownloader_ChromeExtension/issues/2

**Comment by soloam** [comment]
I'm having the same problem, but if I run youtube-dl in the command line it works and returns the movie. Any news on this?

Thank you

**Comment by akentner** [comment]
Same problem over here: 
A link via youtube-dl in nextcloud doesn't work ("Unable to retrieve true YouTube video URL"), but from cmdline it works.

Any idea on that problem or any idea how to debug this?

Thanks

**Comment by e-alfred** [comment]
@akentner @soloam Which downloader do you use? Curl or Aria2c? You need either of them set up because youtube-dl is only used for retrieving the youtube URL. Do you enter the URL on the web interface or using the browser extension? The bug described here is not fixed yet.

**Comment by ion-lane** [comment]
Understood. Change patch to YouTube DL Binary `/usr/local/bin/youtube-dl` on `/usr/bin/youtube-dl`

**Comment by e-alfred** [comment]
The problem is that api.php does not get the path for the youtube-dl binary. Therefore it stays NULL and no real download links are generated. As a dirty fix to set the youtube-dl path directly in this line instead of `$this->YTDLBinary`: https://github.com/e-alfred/ocdownloader/blob/624838675e923acc47175a197f49de49cb5c9e90/controller/lib/youtube.php#L51

I will fix this in the next release.

**Comment by Pechente** [comment]
The suggested solution does not work for me. Using youtube-dl manually and downloading other files works without any problem. The path to the youtube-dl binary is also set correctly and I tried both curl and aria2c.

**Comment by aquaritus** [comment]
Despite using the new version with the above mentioned fix, I have the same issue.

**Comment by e-alfred** [comment]
This is fixed by https://github.com/e-alfred/ocdownloader/commit/019888a4943c1be14fac1aac0345ac4d32823ce7.

**Comment by nokoa77** [comment]
Hi, I still found the same bug in version 1.7.8.
My solution : 
> sudo cp /usr/local/bin/youtube-dl /usr/bin/youtube-dl
and then it worked !

**Comment by sudosu0** [comment]
> Hi, I still found the same bug in version 1.7.8.
> My solution :
> 
> > sudo cp /usr/local/bin/youtube-dl /usr/bin/youtube-dl
> 
> and then it worked !

IMO it's better `ln -s /usr/local/bin/youtube-dl /usr/bin/youtube-dl`

**Comment by p6002** [comment]
I copied YouTube-dl to the correct location and checked it in admin settings. A green "saved" appeared so it was recognized.
Even so, I still can't download the video from YT. ocDownloader "does not recognize YouTube link"
